### ISSUE TITLE
Important: php::microtime(true) now fails to compile in strict mode on scpp 0.1.53

### ISSUE THREAD

**Issue by alexstanciu-1** [alexstanciu-1/simplecpp#141]
On `scpp 0.1.53`, a minimal strict repro using `php::microtime(true)` now fails during codegen/lowering.

Minimal repro:

```php
namespace OM3\Tools\Php_Microtime_Repro;

class Main
{
	public static function run(): void
	{
		$started = php::microtime(true);
		echo ($started > 0.0) ? "ok\n" : "bad\n";
	}
}

Main::run();
```

Observed compiler failure:

```text
../generated/main.cpp:7:37: error: parse error in template argument list
../generated/main.cpp:7:49: error: no matching function for call to '_static<<expression error> >(...)'
```

Generated C++:

```cpp
auto started = ::scpp::php::_static<php>([&]() -> decltype(auto) { return php::microtime(static_cast<bool_t>(true)); });
```

So the generated `_static<php>` template argument is invalid in this context.

This also blocks current OpenM3 shared strict code in `base/db/structure_builder.phs`, where timing metrics use `php::microtime(true)`.

Local isolated repro path:
- `tools/php_microtime_repro/main.phs`

Expected:
- builds and runs normally

Observed:
- compile-time failure on `0.1.53`
